[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
# Note: solc path configured for build environment
# In production, Foundry will auto-download the correct version
solc = "/tmp/solc-0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
